In [1]:
import pandas as pd
import numpy as np

In [2]:
PATH = 'G:/Dataset1.csv'
df1 = pd.read_csv(PATH)

In [3]:
df1

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,Temparetue,Rainfall,Humidity,Sun hours
0,West Bengal,BARDHAMAN,2009,Winter,Rice,416657.0,1231421.0,19.1,46,63.0,9.1
1,West Bengal,BARDHAMAN,2009,Autumn,Rice,17119.0,52128.0,22.1,341,81.0,8.1
2,West Bengal,BARDHAMAN,2009,Rabi,Urad,10.0,6.0,20.3,171,66.0,9.0
3,West Bengal,BARDHAMAN,2009,Kharif,Soyabean,3.0,2.0,26.9,1189,80.0,8.2
4,West Bengal,BARDHAMAN,2009,Autumn,Rice,17119.0,52128.0,22.1,341,81.0,8.1
...,...,...,...,...,...,...,...,...,...,...,...
5589,West Bengal,HOOGHLY,2019,Summer,Groundnut,13267.0,29037.0,30.6,295,68.0,9.5
5590,West Bengal,HOOGHLY,2019,Summer,Sesamum,40756.0,41239.0,30.5,295,68.0,9.5
5591,West Bengal,HOOGHLY,2019,Autumn,Rice,6157.0,18096.0,27.3,264,83.4,8.2
5592,West Bengal,HOOGHLY,2019,Annual,Sugarcane,830.0,149289.0,25.9,1617,79.0,8.8
5593,West Bengal,HOOGHLY,2019,Kharif,Jute,22933.0,522038.0,28.6,1344,81.6,8.4

In [4]:
from __future__ import print_function
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn import tree
import warnings
warnings.filterwarnings('ignore')

In [5]:
s=input("Enter The District Name: ")
 
df = df1.loc[df1['District_Name'] == s] 
features = df[['Crop_Year','Area','Temparetue','Rainfall','Humidity','Sun hours']]
target = df['Crop']
labels = df['Crop']

# Initializing empty lists to append all model's name and corresponding name
acc = []
model = []

from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(features,target,test_size = 0.25,random_state =2)


from sklearn.tree import DecisionTreeClassifier

DecisionTree = DecisionTreeClassifier(criterion="entropy",random_state=2,max_depth=5)

DecisionTree.fit(Xtrain,Ytrain)

predicted_values = DecisionTree.predict(Xtest)
x = metrics.accuracy_score(Ytest, predicted_values)
acc.append(x)
model.append('Decision Tree')
print("DecisionTrees's Accuracy is: ", x*100)

#print(classification_report(Ytest,predicted_values))


from sklearn.naive_bayes import GaussianNB

NaiveBayes = GaussianNB()

NaiveBayes.fit(Xtrain,Ytrain)

predicted_values = NaiveBayes.predict(Xtest)
x = metrics.accuracy_score(Ytest, predicted_values)
acc.append(x)
model.append('Naive Bayes')
print("Naive Bayes's Accuracy is: ", x*100)

#print(classification_report(Ytest,predicted_values))


from sklearn.svm import SVC

SVM = SVC(gamma='auto')

SVM.fit(Xtrain,Ytrain)

predicted_values = SVM.predict(Xtest)

x = metrics.accuracy_score(Ytest, predicted_values)
acc.append(x)
model.append('SVM')
print("SVM's Accuracy is: ", x*100)

#print(classification_report(Ytest,predicted_values))


from sklearn.linear_model import LogisticRegression

LogReg = LogisticRegression(random_state=2)

LogReg.fit(Xtrain,Ytrain)

predicted_values = LogReg.predict(Xtest)

x = metrics.accuracy_score(Ytest, predicted_values)
acc.append(x)
model.append('Logistic Regression')
print("Logistic Regression's Accuracy is: ", x*100)

#print(classification_report(Ytest,predicted_values))


from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(n_estimators=20, random_state=0)
RF.fit(Xtrain,Ytrain)

predicted_values = RF.predict(Xtest)

x = metrics.accuracy_score(Ytest, predicted_values)
acc.append(x)
model.append('RF')
print("RF's Accuracy is: ", x*100)

#print(classification_report(Ytest,predicted_values))

y = int(input("Enter the Year: "))
a = float(input("Enter the Area: "))
t = float(input("Enter the Tempareture: "))
r = float(input("Enter the Rainfall: "))
h = float(input("Enter the Humidity: "))
sh = float(input("Enter the Sun hour: "))
data = np.array([[y,a,t,r,h,sh]])
prediction = DecisionTree.predict(data)
print("PREFERABLE CROP : "+prediction)

Enter The District Name: HOOGHLY
DecisionTrees's Accuracy is:  75.0
Naive Bayes's Accuracy is:  75.43478260869566
SVM's Accuracy is:  95.86956521739131
Logistic Regression's Accuracy is:  54.78260869565217
RF's Accuracy is:  96.08695652173913
Enter the Year: 2022
Enter the Area: 4000
Enter the Tempareture: 26
Enter the Rainfall: 750
Enter the Humidity: 79
Enter the Sun hour: 9
['PREFERABLE CROP : Rice']